# Default Generation Parameters
DEFAULT_WIDTH = 1024
DEFAULT_HEIGHT = 1024
DEFAULT_SDXL_STEPS = 28
DEFAULT_FLUX_STEPS = 8
DEFAULT_SDXL_CFG = 7.0
DEFAULT_FLUX_CFG = 1.0
DEFAULT_SAMPLER = "Euler a"
DEFAULT_SCHEDULER = "Normal"
